asset_path: /home/kenzy/isaac_so_arm101/src/isaac_so_arm101/tasks/pick_place/assets/bowl.obj
usd_dir: /home/kenzy/isaac_so_arm101/src/isaac_so_arm101/tasks/pick_place/assets
usd_file_name: bowl.usd
force_usd_conversion: true
make_instanceable: false
mass_props:
  mass: 1.0
  density: null
rigid_props:
  rigid_body_enabled: true
  kinematic_enabled: null
  disable_gravity: true
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: null
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: true
  contact_offset: null
  rest_offset: null
  torsional_patch_radius: null
  min_torsional_patch_radius: null
mesh_collision_props:
  usd_func: pxr.UsdPhysics:MeshCollisionAPI
  physx_func: pxr.PhysxSchema:PhysxConvexDecompositionCollisionAPI
  hull_vertex_limit: null
  max_convex_hulls: 32
  min_thickness: null
  voxel_resolution: null
  error_percentage: null
  shrink_wrap: true
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2026-05-17 at 16:50:50.
##
